---
sudo: required
dist: xenial

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get -y install make

script:
  - cd docker/
  - make init
  - make run_node
  - make clean
  - make rm
  - make build_images

branches:
  only:
    - master
